function escapeXml(value = '') {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/**
 * Generate a simple MA3-compatible plugin XML wrapper that points to the LUA entry file.
 * @param {Object} config
 * @param {string} config.pluginName
 * @param {string} config.version
 * @param {string} config.description
 * @param {string} config.luaFileName
 * @param {string} [config.entryPoint='main']
 * @returns {string}
 */
export function generatePluginXml(config) {
  const {
    pluginName,
    version,
    description,
    luaFileName,
    entryPoint = 'main',
  } = config

  const safePluginName = escapeXml(pluginName || 'GMA3 Disco Pilot')
  const safeVersion = escapeXml(version || '1.0.0')
  const safeDescription = escapeXml(description || 'Generated by Disco Pilot')
  const safeLuaFileName = escapeXml(luaFileName || 'GMA3_Disco_Pilot_Plugin.lua')
  const safeEntryPoint = escapeXml(entryPoint)

  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<MA3Plugin>',
    `  <Plugin Name="${safePluginName}" Version="${safeVersion}">`,
    `    <Description>${safeDescription}</Description>`,
    '    <Script>',
    `      <File>${safeLuaFileName}</File>`,
    `      <EntryPoint>${safeEntryPoint}</EntryPoint>`,
    '    </Script>',
    '  </Plugin>',
    '</MA3Plugin>',
    '',
  ].join('\n')
}
